### ISSUE TITLE
controleur : programmer un kn -> fiabiliser la veille

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#101]

**Comment by killiankopp** [comment]
**customer and user**
FE - controleur

**Scrum brief**
En tant que controleur, je veux pouvoir programmer un kn sans risque d'erreur afin de fiabiliser la veille.
La création d'un kn est source d'erreurs. Il ne faut plus qu'un contrôleur puisse créer n'importe quel type de kn pour n'importe quel personnel.
Un contrôleur est habilité à faire passer certain KN, il ne doit pas voir les autres. Il ne pourra faire passer un KN parmi ces derniers que pour des personnes habilités.

**Brief**

**Todo display**
- [ ] wireframe @killiankopp 
- [ ] check wireframe @killiankopp 
- [ ] prototype @marilehoux   
- [ ] check prototype @killiankopp  
- [ ] codage HTML / CSS @marilehoux  
- [ ] check HTML / CSS @Guillaume35 
- [ ] codage JS @marilehoux 
- [ ] check JS @Guillaume35 

**Todo data**
- [ ] specs routes api @killiankopp 
- [ ] check specs routes api @killiankopp 
- [ ] specs tests @killiankopp 
- [ ] check tests @killiankopp 
- [ ] uml @heligonSeb 
- [ ] check uml @killiankopp 
- [ ] intégration database @heligonSeb 
- [ ] check database @killiankopp 
- [ ] codage routes @killiankopp 
- [ ] check routes @Guillaume35 
- [ ] codage tests @killiankopp 
- [ ] check tests @killiankopp 

**Todo validation**
- [ ] tests unitaires @killiankopp 
- [ ] conformité cahier des charges @killiankopp  
- [ ] validation par le client @killiankopp 

**Additional information / Code indication**
Nous allons partir des habilitations pour créer un KN et ainsi en assurer la veille.

**Comment by killiankopp** [comment]
[page_sans_titre.pdf](https://github.com/pebble-solutions/App-QSE-controle/files/11383099/page_sans_titre.pdf)

**Comment by killiankopp** [comment]
La programmation d'un KN va être scindée en 2 étapes

## Etape 1 : type de KN
- Choix du type d'habilitation (parmi ceux pour lequel le contrôleur est compétent)
- Choix de la date
- Suppression des autres informations

## Etape 2 : choix du personnel
- Choix du personnel (parmi ceux ayant une habilitation active pour le type d'habilitation)
- Choix du projet (parmi ceux actif à la date)

**Comment by killiankopp** [comment]
## bison futé
Choix du personnel
GET api/v2/controle/habilitation + habilitation_id = x + active = 1
