### ISSUE TITLE
RQSE : déverrouiller un contrôle -> demander à un contôleur de faire des modifications

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#2]
**customer and user**
FE - RQSE / DE

**Scrum brief**
En tant que RQSE, je veux pouvoir déverrouiller un contrôle afin de demander à un contrôleur de faire des modifications ou des corrections.

**Brief**
Un contrôle est verrouillé après un laps de temps donné. ll peut arriver que pour une raison X ou Y, il soit demander à un contrôleur de revoir un tiem, un commentaire et de compléter un KN. Cette demande émanera d'un responsable qui pourra déverrouiller le KN en vue de sa modification par le contrôleur.

**Additional information**

**Roles**
- design team :  
- dev team : @marilehoux @Guillaume35 

**Pré-requis**

Le développement est interfaces ne peut pas être réalisée sans les rôles et les caractéristiques du personnel.

**Todo**
- [x] @Guillaume35 modifier la table InformationLiaison
- [x] @Guillaume35 ajouter les règles sur les fonctions de la classe InformationLaision
- [x] @Guillaume35 créer la route d'API de déverrouillage
- [x] @marilehoux Créer les interfaces de déverrouillage sur la console du responsable
- [ ] @killiankopp Ajouter le système de notification de déverrouillage au contrôleur : la notification est enregistrée, mais il faut qu'elle soit envoyée par mail.
- [x] @Guillaume35 Renvoyer la liste des notes sur les données des collectes
- [x] @Guillaume35 Créer la route d'API de validation avec les nouvelles règles sur la classe InformationLiaison
- [x] @marilehoux Modifier le bouton de validation de collecte pour passer par la route api/v2/collecte/:id/validate (contacter guillaume pour le faire sur une branche à part)
- [x] @marilehoux Afficher l'historique des notes sur la collecte dans la vue consultation

**Comment by Guillaume35** [comment]
Les modifications post-validation par le contrôleur peuvent se faire uniquement par le rôle "Responsable QSE" et avant la vérification définitive (visa responsable). Actions post-modification :

- Notifier l'opérateur d'une modification
- Notifier le contrôleur

**Comment by Guillaume35** [comment]
Modifier les règles de la validation :

Actions lors de la validation par le contrôleur

- Enregistrer mkg_information__liaison.date_done à NOW()
- Enregistrer mkg_information__liaison.done à "OUI"
- Enregistrer mkg_information__liaison.unlocked à NULL

**Comment by Guillaume35** [comment]
Modifier les règles de verrouillage :

Ajout de la règle suivante sur getLocked() de InformationLiaison :

- **locked** retourne `false` : si **unlocked** est `true` et que **date_done** est `false`

**Comment by Guillaume35** [comment]
Créer une route d'API pour le déverrouillage

`POST /api/v2/collecte/:id/unlock`

Le contrôleur doit appeler une méthode InformationLiaison::unlock() qui réalisera les opération suivantes :

- [ ] mkg_information__liaison.unlocked à `true`
- [ ] mkg_information__liaison.date_done à `false`
- [ ] mkg_information__liaison.done à _NON_
- [ ] Création d'une note pour historiser le déverrouillage (date, responsable).
- [ ] Notifier la note au contrôleur

**Comment by Guillaume35** [comment]
Le déverrouillage engendre une perte de données sur date_done. Solution :

- date_done enregistre la dernière date de validation du contrôleur
- lors de la validation, une note d'historique est automatiquement ajoutée pour conserver la date de validation.

Créer la route d'API de validation

`POST /api/v2/collecte/:id/validate`

Le Controller appel une méthode InformationLiaison::validate() qui réalisera les opérations suivantes si la collecte est déverrouillées sans date_done :

- mkg_information__liaison.done à "OUI" (la méthode setDone("OUI") ajoute déjà la date_done
- Création d'une note d'historique "{login} a validé"

**Comment by marilehoux** [comment]
@marilehoux modifier la route de validation dans la vue "collecteVerif"

**Comment by killiankopp** [comment]
@Guillaume35 peux-tu documenter les routes dans swagger
