### ISSUE TITLE
En tant qu'administrateur je veux pouvoir créer des caractéristiques afin de commencer à tester le transfert des habilitations vers une fonctionnalité dédiée

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#72]
Les habilitations sont en fait des types de document. Cela pose de nombreux problèmes. Après réflexion, nous avons décidé de créer une table "caractéristiques" et une autre de liaison entre le personnel et ces caractéristiques pour remplacer le comportement des habilitations. Cette fonctionnalité vise à étendre les possibilités en ajoutant les habilitations mais aussi dans le même temps n'importe quelle caractéristique à un personnel.

**Comment by killiankopp** [comment]
**Code indication**
**Table `mkg_characteristic`**

| colonne | type de donnée | fk | Description |
| ------ | ------ | ------ | ------ |
| label | VARCHAR(100) | | |
| appliant_method | ENUM('procedure', 'nomination') | | Méthode d’acquisition de la caractéristique |
| procedure_id | INT | mkg_projet(id) | Projet de type procédure lorsque appliant_method est de type "procédure" |
| role_id | INT | mkg_roles(id) | ID du role autorisé à accorder la caractéristique à un personnel lorsque appliant_method est de type "nomination" |
| step_control | INT | Pas de veille d'habilitation en jours |
| information__groupe_id | INT | mkg_information__groupe(id) | ID du formulaire à utiliser lors de la programmation d'un contrôle sur l'habilitation |
| expiration | INT | Durée de conservation de l’habilitation |

**Table `mkg_structure__personnel_characteristic`**

| colonne | type de donnée | fk | Description |
| ------ | ------ | ------ | ------ |
| personnel_id | INT | mkg_structure__personnel(id) | ID du personnel ayant l’habilitation |
| characteristic_id | INT | mkg_characteristic(id) | ID de la caractéristique à appliquer |
| dd | DATE | | Date de début de l'habilitation. Cette date est appliqué automatiquement à la date du jour de création de l'enregistrement ou manuellement à une autre date |
| df | DATE | | Date de fin de l'habilitation. Cette date est calculé automatiquement avec le champ `expiration` de la table `mkg_characteristic` |
| last_control | DATETIME | | Date du dernier contrôle réalisé sur cette habilitation |
| collecte_id | INT | mkg_information__liaison(id) | ID du dernier contrôle réalisé sur cette habilitation |

**Comment by killiankopp** [comment]
**Todo**
- [ ] @heligonSeb modélisation UML
- [ ] @killiankopp création des tables dans la base de données
- [ ] @killiankopp création des fiches et listes (ancienne version) pour manipuler les données
