### ISSUE TITLE
RQSE : verrouillage auto KN >> poursuite cycle validation

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#73]
**customer and user**
FE / RQSE (Virginie)

**Scrum brief**
En tant que responsable QSE, je veux que les KN soient automatiquement verrouillés après un laps de temps que j'aurais défini au préalable type de KN par type de KN afin qu'ils ne puissent plus être modifiés et ainsi suivre leurs cycles de validation

**Brief**
Ajouter au niveau du formulaire une variable "temps avant verouillage" exprimé en jours.
Lors de l'utilisation d'un formulaire pour créer une collecte, celle-ci devra être notée comme verrouillée (à la volée) si le délai est dépassé. Il faudra tenir compte de la date de début de collecte et non de la date de création car des collectes peuvent être programmées à l'avance.

**Additional information**
Une autre issue permettra le passage en mode modification en restreignant cette possibilité aux seules personnes habilitées à le faire.

**Roles**
- head of issue : @killiankopp 
- design team :  RAS
- dev team : @killiankopp @heligonSeb @marilehoux 

**Todo**
- [x] @heligonSeb MAJ UML
- [x] @killiankopp modification de la table
- [x] @killiankopp création de la fonction de verouillage
- [x] @marilehoux intégration frontend
- [x] @Guillaume35 intégration locked_timeout sur le formulaire de modification du groupe
- [x] Afficher le nombre de jours restants pour réaliser le contrôle basé sur `groupe_lock_timeout` et `date_start` des collectes @marilehoux 
- [x] Afficher un verrou avec bascule automatique en mode consultation lorsque `locked` est true sur une collecte @marilehoux 

**Code indication**
Créer un attribut lock_timeout sur la classe InformationGroupe.
La valeur stockée est exprimée en jours. C'est le délai de verrouillage des collectes (InformationLiaison) après validation (InformationLiaison.d_done non NULL).
Si la valeur est NULL, la collecte ne se verrouille jamais.

Ajouter un attribut `lock_timeout` la classe **InformationGroupe** :

- Type : int
- Défaut : NULL
- Attribut : `lock_timeout`

Sur la classe **InformationLiaison**, ajouter une méthode `getLocked` qui retourne `true` si la collecte est verrouillée.

**Comment by killiankopp** [comment]
Quelle est la date de départ du verrouillage du KN ? Qui peut modifier le KN et sous quelles conditions ? Est-ce un verrouillage après avec terminé ou depuis le début ?

**Comment by killiankopp** [comment]
La date à prendre en compte pour le verrouillage est la date de début du KN (la date à laquelle il a été réellement débuté). Cette date + le temps avant verrouillage auto nous donne la date butoire après laquelle il ne sera plus modifiable (terminé ou pas terminé). Le contrôleur a donc un délai (paramétrable par un admin) pour finaliser / terminer son contrôle, passé ce délai il est automatiquement rendu non modifiable.

Le RQSE ou le Directeur d'exploitation peut rouvrir un contrôle et le rendre à nouveau modifiable par le contrôleur initial. (cette fonctionnalité devra être paramétrable mais ne fais pas l'objet de cette issue)

**Comment by Guillaume35** [comment]
**Limitation de la demande**

- Le contrôle ne se verrouillera que après le début de sa réalisation. En conséquence, **le contrôleur disposera d'un temps illimité pour débuter son contrôle**. Exemple : un contrôle programmé le 01/03/2023 peut être débuté le 20/03/2023 et verrouillé automatiquement à J+3 de la date de début, donc le 21/02/2023
- **Le verrou est automatique**. Ça n'est pas ne valeur enregistrée mais calculée. Pour imaginer une option de réouverture du contrôle, il faudra travailler sur une valeur `unlock` qui elle sera enregistrée. Il sera alors nécessaire de déterminer les conditions requises pour un déverrouillage et les rôles pouvant intervenir sur cette opération.

**Actions à réaliser :**

- [ ] Ajouter un champ `date_start` sur InformationLiaison qui enregistre la première action débuter @Guillaume35 
- [ ] Modifier la fonction `computeLocked` sur InformationLiaison pour intégrer les règles décrites ci-après @Guillaume35 
- [ ] Créer une mise à jour pour migrer tous les attributs `dc` de la première réponse enregistrée dans les attributs `date_start` des InformationLiaison pour les contrôles ayant des réponses enregistrées. Les contrôles n'ayant pas de réponse enregistrés sont considérés comme non-débutés.

**Règles de verrouillage**

Un contrôle est verrouillé si il répond à une des conditions suivantes :

- L'attribut `done` est _OUI_
- `date_start` + `lock_timeout` < date du jour

**Comment by Guillaume35** [comment]
**Actions à réaliser pour l'intégration dans l'interface**

- [ ] Afficher le nombre de jours restants pour réaliser le contrôle basé sur `groupe_lock_timeout` et `date_start` des collectes @marilehoux 
- [ ] Afficher un verrou avec bascule automatique en mode consultation lorsque `locked` est true sur une collecte @marilehoux

**Comment by killiankopp** [comment]
ajouter un verrouillage sur la date de kn + temps donné : la date du contrôle prévu
le champ done ne doit servir qu'à dire que le kn est terminé
