### ISSUE TITLE
En tant que dirigeant, je veux pouvoir déterminer le taux de veille et le type de veille pour un type de KN afin de créer une chaîne hiérarchique de contrôle

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#74]
**Brief**
L'idée est de répondre à la demande KN niveau I et KN niveau II. 

**Additional information**
Une veille sur la signature des contrats, le matériel, les procédures, ... tout ceci devrait pouvoir être réalisé avec ce genre d'outil.

**Code indication**
Ajouter les champs de veille sur InformationGroupe

| Colonne | Type de donnée | fk | Description |
| --- | --- | --- | --- |
| veille_taux | DECIMAL(3,2) | | Taux de veille sur les réponses à ce questionnaire |
| veille_groupe_id | INT | mkg_information__groupe(id) | Formulaire de veille à utiliser |
| veille_characteristic_id | INT | mkg_characteristic(id) | Habilitation requise pour faire passer la veille |

**Todo**
- [ ] @killiankopp @Guillaume35 voir pour étendre ce principe à d'autres apps

**Comment by killiankopp** [comment]
J'ai créé la table mkg_information__veille via la classe_information_veille
- [ ] @heligonSeb mettre à jour UML
- [ ] @heligonSeb ajouter champ TLC / TLI à mkg_information__veille

**Comment by killiankopp** [comment]
Les routes pour manipuler les veilles sont en place.
GET /v2/controle/veille
POST /v2/controle/veille
GET /v2/controle/veille/{id}
PATCH /v2/controle/veille/{id}
DELETE /v2/controle/veille/{id}

Une veille doit être rattaché à un tlc (et un tli). Ce rattachement n'est pas (pour le moment) renommé pour en simplifier la compréhension, il faut donc utiliser les "vrais" codes. Pour veiller sur un type d'habilitation (habilitation_type_id) il faut utiliser le code Characteristic (valeur de tlc) et le contenu pour tli.

@marilehoux : peux-tu faire les formulaires pour manipuler les veilles ?

**Comment by killiankopp** [comment]
il manque les interfaces graphiques pour le faire
