### ISSUE TITLE
Direction : comparer un item en fonction de la moyenne -> positionner un opérateur

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#82]
**customer and user**
FE / direction

**Scrum brief**
En tant que responsable, je veux savoir comment se positionne l'opérateur sur un item en fonction de la moyenne des opérateurs sur cette item afin de voir s'il faut retravailler un point collectivement ou individuellement.

**Brief**
L'idée est de savoir rapidement comment se positionne l'opérateur par rapport à ses collègues évalués sur le même item. 

**Todo display**
- [ ] wireframe @Modreymod 
- [ ] check wireframe @killiankopp 
- [ ] prototype @Modreymod 
- [ ] check prototype @killiankopp  
- [ ] codage HTML / CSS @Modreymod 
- [ ] check HTML / CSS @Guillaume35 
- [ ] codage JS @marilehoux 
- [ ] check JS @Guillaume35 

**Todo data**
- [ ] specs routes api @Modreymod 
- [ ] check specs routes api @killiankopp 
- [ ] specs tests @killiankopp 
- [ ] check tests @killiankopp 
- [ ] uml @heligonSeb 
- [ ] check uml @killiankopp 
- [ ] intégration database @heligonSeb 
- [ ] check database @killiankopp 
- [ ] codage routes @killiankopp 
- [ ] check routes @Guillaume35 
- [ ] codage tests @killiankopp 
- [ ] check tests @killiankopp 

**Todo validation**
- [ ] tests unitaires @killiankopp 
- [ ] conformité cahier des charges @killiankopp  
- [ ] validation par le client @killiankopp 

**Additional information / Code indication**
@killiankopp pense à un code à 3 pictos up - equal - down

**Comment by Guillaume35** [comment]
<img width="1321" alt="notation-moyenne" src="https://github.com/pebble-solutions/App-QSE-controle/assets/945411/c8985225-8d56-48f1-984e-3d7998ef3e5e">
